### ISSUE TITLE
move-window doesnt work 

### ISSUE THREAD

**Issue by neerajbadlani** [sainnhe/tmux-fzf#35]
It return an error , on printing the values : 
it generates this : 
tmux move-window -a -s session1:2 -t vagrant:4:bash

target doesnt look correct .

**Comment by neerajbadlani** [comment]
Same for link-window as well , sed statement might have some mistake

**Comment by sainnhe** [comment]
This should be fixed via faceb3d.

**Comment by neerajbadlani** [comment]
Thanks , Will give it a try soon !

**Comment by FrostyX** [comment]
I installed `tmux-fzf` today and I think `move-window` still doesn't work.
